 function bigFunction(arr) {
   function findDuplicates(arr) {
     let result = [];
     let seen = new Set();
     for (let i = 0; i < arr.length; i++) {
       if (seen.has(arr[i])) {
         continue;
       }
       seen.add(arr[i]);
       let count = 1;
       for (let j = i + 1; j < arr.length; j++) {
         if (arr[j] === arr[i]) {
           count++;
         }
       }
       if (count > 1) {
         result.push([arr[i], count]);
       }
     }
     return result.length > 0 ? result : [{}];
   }
   return findDuplicates(arr);
 }

// module.exports = { bigFunction, findDuplicates };
// Date: 2024-12-18
// Author: Generated by GoCodeo.


const { expect, assert } = require("chai");

    describe('bigFunction', () => {
        it('should return an array of duplicates when input has duplicates', () => {
            // Arrange
            const input = [1, 2, 3, 2, 1, 4];
            const expectedOutput = [[1, 2], [2, 2]];
    
            // Act
            const result = bigFunction(input);
    
            // Assert
            expect(result).to.deep.equal(expectedOutput);
        });
    });

